version: '3.8'

services:
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        # ports:
        #     - "3000:3000" # закрыть порт 3000, что
        expose: 
            - "3000" # сделать порт видимым только для nginx
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
            - IS_PRODACTION=true 
            - SSL_ENABLED=false # FastAPI не будет использовать SSL в продакшене
        env_file:
            - .env
        depends_on:
            - db
        
        # volumes:
        #     - ./backend:/app  # для hot reload в разработке

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./backend/dist:/usr/share/nginx/html  # Монтируем dist непосредственно в корень
            - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL-сертификаты
        depends_on:
            - backend
        restart: always

volumes:
    postgres_data:
