"""update database schema with user_id fields

Revision ID: 00232bd1ba3a
Revises: f92d42ebf671
Create Date: 2025-08-01 17:07:12.116128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00232bd1ba3a'
down_revision: Union[str, Sequence[str], None] = 'f92d42ebf671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filters', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'filters', 'users', ['user_id'], ['id'])
    op.add_column('queries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'queries', 'users', ['user_id'], ['id'])
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'queries', type_='foreignkey')
    op.drop_column('queries', 'user_id')
    op.drop_constraint(None, 'filters', type_='foreignkey')
    op.drop_column('filters', 'user_id')
    # ### end Alembic commands ###
