"""Added SubTask.created_at and SubTask.finished_at

Revision ID: 2f3f08cdd9a0
Revises: 389deddb3a6f
Create Date: 2025-08-13 08:15:06.041258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3f08cdd9a0'
down_revision: Union[str, Sequence[str], None] = '389deddb3a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtasks', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subtasks', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtasks', 'finished_at')
    op.drop_column('subtasks', 'created_at')
    # ### end Alembic commands ###
