import { atom } from 'jotai'
import { TypeQuery } from '@mytype/typeSaveQueries'

export const atomQueryList = atom<TypeQuery[]>([
    {
        id: 1,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 2,
        name: "Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 3,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 4,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 5,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 6,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 7,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 8,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 9,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 10,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 11,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 12,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 13,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 14,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 15,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 16,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 17,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 18,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 19,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 20,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    },
    {
        id: 21,
        name: "Все задачи",
        descr: "This is a default query that retrieves all tasks.",
        q: "",
        infilt: [],
        exfilt: [],
        crange: "",
        arange: "",
        drange: "",
        irange: "",
        donerule: "",
        failrule: "",
        inrisk: [],
        exrisk: [],
        inimpact: [],
        eximpact: [],
        sort: [],
        is_default: false,
        page: 1
    }
])

export const queryAllTasks:TypeQuery = {
    id: -1,
    name: "Все задачи",
    descr: "This is a default query that retrieves all tasks.",
    q: "",
    infilt: [],
    exfilt: [],
    crange: "",
    arange: "",
    drange: "",
    irange: "",
    donerule: "",
    failrule: "",
    inrisk: [],
    exrisk: [],
    inimpact: [],
    eximpact: [],
    sort: [],
    is_default: false,
    page: 1
}

export const atomQuerySelect = atom<TypeQuery|null>({...queryAllTasks})

type TypeSamplingStatus = 'idle' | 'loading' | 'success' | 'error'

export const samplingStatus = atom<TypeSamplingStatus>("idle")